{{ if and .Values.rbac.create .Values.rbac.createrole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "vault-gcr-secrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "vault-gcr-secrets.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{ end }}
