apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJQTEFDRUhPTERFUiI6eyJ1c2VybmFtZSI6IlBMQUNFSE9MREVSIiwicGFzc3dvcmQiOiJQTEFDRUhPTERFUiIsImF1dGgiOiJVRXhCUTBWSVQweEVSVkk2VUV4QlEwVklUMHhFUlZJPSJ9fX0=
kind: Secret
metadata:
  name: {{ .Values.secret.name | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "vault-gcr-secrets.labels" . | indent 4 }}
type: {{ .Values.secret.type | quote }}
