{{ $labels := include "vault-gcp-secrets.labels" . | indent 4 }}
{{ range .Values.additionalSecrets }}
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJQTEFDRUhPTERFUiI6eyJ1c2VybmFtZSI6IlBMQUNFSE9MREVSIiwicGFzc3dvcmQiOiJQTEFDRUhPTERFUiIsImF1dGgiOiJVRXhCUTBWSVQweEVSVkk2VUV4QlEwVklUMHhFUlZJPSJ9fX0=
kind: Secret
metadata:
  name: {{ .name | quote }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ $labels }}
type: {{ default $.Values.secret.type .type | quote }}
{{ end }}
