{{ if and .Values.rbac.create .Values.rbac.createrole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "vault-gcp-secrets.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "vault-gcp-secrets.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - {{ .Values.secret.name | quote}}
{{- range .Values.additionalSecrets }}
  - {{ .name | quote }}
{{- end }}
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{ end }}
